# Generated by Django 5.1.1 on 2024-10-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='text',
        ),
        migrations.AlterField(
            model_name='document',
            name='filepath',
            field=models.FilePathField(null=True, path='D:\\workshop\\python\\ongoing\\howa_resminama\\media'),
        ),
    ]
