# Generated by Django 5.1.1 on 2024-10-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_text_alter_document_filepath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscussionText',
        ),
    ]
